spring:
  profiles: default
  main:
    banner-mode: 'off'
logging:
  level:
    org.springframework.web: ERROR
    com.morrisons: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n-%X{mdcData}%5p'
management:
  security:
    enabled: false
cloud:
  aws:
    region:
      static: eu-west-1
      auto: true
    stack:
      auto: false
pers:
  proxyConfig:
    useProxy: false
    proxyHost: null
    proxyPort: null
    proxyUserName: null
    proxyPassword: null
  s3:
    folderName: outbound/transactions/bballocs/pending
    bucketName: mdev.xxwmm.supplychain.relex.eeeeeeeeee
    fileName: null
    fileExtn: dat
  databaseConfig:
    username: api_stockmovementgenerator_v1_user
    password: Ysfv37dhjk88s
    url: jdbc:postgresql://rds-euw1-devpg-freshbackbone-001-v00.ca107skwgezh.eu-west-1.rds.amazonaws.com:5432/api_stockmovementgenerator_v1_db_dev
    stockMovementStg: stock_movement_stg
  dSDOrdersConfig:
    uri: https://api.morrisons.com/wholesale/v2/customers/{customerId}/supplier/{supplierName}/directorders
    apiKey: l6dNLwHbqpnhvUVPqhaLNCjA0qKdFo36
    authorization: Basic bDZkTkx3SGJxcG5odlVWUHFoYUxOQ2pBMHFLZEZvMzY6MERtY1NsZVRHWkJ6QURGbg==
  updateItemConfig:
    uri: https://api.morrisons.com/wholesale/v2/customers/{customerId}/suppliers/{supplierName}/orders/{orderId}/items
    apiKey: l6dNLwHbqpnhvUVPqhaLNCjA0qKdFo36
    authorization: Basic bDZkTkx3SGJxcG5odlVWUHFoYUxOQ2pBMHFLZEZvMzY6MERtY1NsZVRHWkJ6QURGbg==
  pollingConfig:
    uri: https://api.morrisons.com/wholesale/v2/customers/{customerId}/directorders/jobs/{jobId}
    apiKey: l6dNLwHbqpnhvUVPqhaLNCjA0qKdFo36
    authorization: Basic bDZkTkx3SGJxcG5odlVWUHFoYUxOQ2pBMHFLZEZvMzY6MERtY1NsZVRHWkJ6QURGbg==
  storeServiceConfig:
    uri: https://api.morrisons.com/wholesale/v1/customers/{customerId}/stores/{storeId}/latest
    apiKey: LHn5X2zrjSlrdFKfhnzruE0gVLPkJCiz
    authorization: Basic TEhuNVgyenJqU2xyZEZLZmhuenJ1RTBnVkxQa0pDaXo6eXgyYXBBNjQzY1drcktBWQ==
  customer:
    indexkey: customerMessageType
    indexvalue: wholesale-dsd-order-processor
  dynamoDbConfiguration:
    dynamoWholesaleConfigTable: dev.xxwmm.wholesale.core.config
    batchLimit: 25
  redis: 
    endpoint: redis://127.0.0.1:6379
    connectionMinimumIdleSize: 10
    connectionPoolSize: 30
    idleConnectionTimeout: 10000
    connectTimeout: 10000
    evn: local